import type { ApplicationBuildRunbook, XuPhase } from "../xu/types";

export const GENERATED_HEADER = [
  "Generated by Xupra DryLake.",
  "Source: drylake.xu.",
  "Do not edit this generated file directly unless you intend to diverge from the approved runbook.",
  "",
].join("\n");

export function bulletList(items: string[]) {
  return items.length > 0 ? items.map((item) => `- ${item}`).join("\n") : "- None recorded.";
}

export function numberedList(items: string[]) {
  return items.length > 0 ? items.map((item, index) => `${index + 1}. ${item}`).join("\n") : "1. No steps recorded.";
}

export function renderRunbookSummary(runbook: ApplicationBuildRunbook) {
  return [
    `# ${runbook.metadata.name}`,
    "",
    `Purpose: ${runbook.intent.purpose || "Not confirmed yet."}`,
    "",
    "## Goals",
    bulletList(runbook.intent.goals),
    "",
    "## Non-Goals",
    bulletList(runbook.intent.nonGoals),
    "",
    "## Constraints",
    bulletList(runbook.intent.constraints),
    "",
    "## Architecture",
    runbook.architecture.summary || "No architecture summary yet.",
  ].join("\n");
}

export function renderPhaseSection(phase: XuPhase) {
  return [
    `## ${phase.id}: ${phase.title}`,
    "",
    `Gate: ${phase.gate}`,
    "",
    "Objective:",
    phase.objective || "No objective recorded.",
    "",
    "Steps:",
    numberedList(phase.steps.map((step) => step.text)),
    "",
    "Acceptance:",
    bulletList(phase.acceptance),
  ].join("\n");
}

