export type PlannedGeneratedFile = {
  logicalPath: string;
  content: string;
  status: "new" | "unchanged" | "would update" | "conflict";
  existingContent?: string;
};

export async function planGeneratedFiles(
  files: Array<{ logicalPath: string; content: string }>,
  readExisting: (logicalPath: string) => Promise<string | null>,
): Promise<PlannedGeneratedFile[]> {
  const planned: PlannedGeneratedFile[] = [];

  for (const file of files) {
    const existingContent = await readExisting(file.logicalPath);

    if (existingContent === null) {
      planned.push({ ...file, status: "new" });
      continue;
    }

    if (existingContent === file.content) {
      planned.push({ ...file, status: "unchanged", existingContent });
      continue;
    }

    planned.push({
      ...file,
      status: existingContent.includes("Generated by Xupra DryLake.") ? "would update" : "conflict",
      existingContent,
    });
  }

  return planned;
}

export function summarizeGeneratedFilePlan(plan: PlannedGeneratedFile[]) {
  const counts = {
    new: 0,
    unchanged: 0,
    "would update": 0,
    conflict: 0,
  };

  for (const item of plan) {
    counts[item.status] += 1;
  }

  return counts;
}

