import { describe, expect, it, vi } from "vitest";

import { createStarterXu } from "../xu/createStarterXu";
import { renderRunbookMd } from "../generators/renderRunbookMd";
import { renderPhasePrompt } from "../generators/renderPhasePrompt";
import { renderAgentsMd } from "../generators/renderAgentsMd";
import { renderClaudeMd } from "../generators/renderClaudeMd";
import { renderCopilotInstructions } from "../generators/renderCopilotInstructions";
import { renderCursorRules } from "../generators/renderCursorRules";
import { renderCodexSkill } from "../generators/renderCodexSkill";
import { renderOpenClawSkill } from "../generators/renderOpenClawSkill";
import { renderGeneratedFiles } from "../generators/renderGeneratedFiles";
import { planGeneratedFiles } from "../generators/planGeneratedFiles";
import { writeGeneratedFiles } from "../generators/writeGeneratedFiles";
import * as vscode from "vscode";

const writes = new Map<string, string>();

vi.mock("vscode", () => {
  class Uri {
    constructor(public path: string, public fsPath = path) {}
    static file(value: string) {
      return new Uri(value, value);
    }
    static joinPath(base: Uri, ...segments: string[]) {
      const path = [base.path.replace(/\/+$/, ""), ...segments].join("/");
      return new Uri(path, path);
    }
    with(next: { path?: string }) {
      return new Uri(next.path ?? this.path, next.path ?? this.fsPath);
    }
  }

  return {
    Uri,
    workspace: {
      fs: {
        createDirectory: vi.fn(),
        writeFile: vi.fn(async (uri: Uri, bytes: Uint8Array) => {
          writes.set(uri.path, new TextDecoder().decode(bytes));
        }),
        readFile: vi.fn(),
      },
    },
  };
});

function runbook() {
  const value = createStarterXu({ prompt: "Build dashboard", mode: "build-app" });
  value.intent.purpose = "Build a dashboard.";
  value.architecture.summary = "Use local extension modules.";
  return value;
}

describe("runbook generators", () => {
  it("renders RUNBOOK.md and phase prompts", () => {
    const value = runbook();

    expect(renderRunbookMd(value)).toContain("Generated by Xupra DryLake.");
    expect(renderPhasePrompt(value, value.phases[0])).toContain("You are executing phase 01-intake");
  });

  it("renders agent-aware phase prompt preambles", () => {
    const value = runbook();
    value.phases[0].agent = "codex";

    expect(renderPhasePrompt(value, value.phases[0])).toContain("You are running as Codex CLI.");
    expect(renderPhasePrompt(value, value.phases[1])).toContain("You are running as Claude Code.");
  });

  it("uses active build-session provider for no-agent phase prompts", () => {
    const value = runbook();

    expect(
      renderPhasePrompt(value, value.phases[1], {
        activeProvider: {
          providerId: "user-ide-ai",
          providerLabel: "User IDE AI",
        },
      }),
    ).toContain("Use the active DryLake build-session provider: User IDE AI.");
  });

  it("keeps explicit phase agent ahead of active build-session provider", () => {
    const value = runbook();
    value.phases[0].agent = "codex";

    const prompt = renderPhasePrompt(value, value.phases[0], {
      activeProvider: {
        providerId: "user-ide-ai",
        providerLabel: "User IDE AI",
      },
    });

    expect(prompt).toContain("You are running as Codex CLI.");
    expect(prompt).not.toContain("Use the active DryLake build-session provider: User IDE AI.");
  });

  it("renders native agent files with generated headers", () => {
    const value = runbook();
    const outputs = [
      renderAgentsMd(value),
      renderClaudeMd(value),
      renderCopilotInstructions(value),
      renderCursorRules(value),
      renderCodexSkill(value),
      renderOpenClawSkill(value),
    ];

    for (const output of outputs) {
      expect(output.startsWith("Generated by Xupra DryLake.")).toBe(true);
    }
  });

  it("plans generated outputs without writing", async () => {
    const files = renderGeneratedFiles(runbook());
    const plan = await planGeneratedFiles(files, async () => null);

    expect(plan.length).toBeGreaterThan(8);
    expect(plan.every((item) => item.status === "new")).toBe(true);
    expect(files.map((item) => item.logicalPath)).toContain(".drylake/generated/AGENTS.md");
  });

  it("detects backup-required overwrites before writing", async () => {
    const files = [{ logicalPath: ".drylake/generated/RUNBOOK.md", content: "Generated by Xupra DryLake.\nnew" }];
    const plan = await planGeneratedFiles(files, async () => "Generated by Xupra DryLake.\nold");

    expect(plan[0].status).toBe("would update");
    expect(plan[0].existingContent).toContain("old");
  });

  it("creates backups before overwriting changed files", async () => {
    writes.clear();
    await writeGeneratedFiles({
      rootUri: vscode.Uri.file("/repo"),
      plan: [
        {
          logicalPath: ".drylake/generated/RUNBOOK.md",
          content: "Generated by Xupra DryLake.\nnew",
          existingContent: "Generated by Xupra DryLake.\nold",
          status: "would update",
        },
      ],
    });

    expect(writes.get("/repo/.drylake/generated/RUNBOOK.md.drylake.bak")).toContain("old");
    expect(writes.get("/repo/.drylake/generated/RUNBOOK.md")).toContain("new");
  });
});
